In [3]:

import numpy as np
import pandas as pd

In [45]:
data = pd.read_csv('/Users/karthjk97/Downloads/data_today.csv')

In [49]:
data = data.iloc[:,0:3]

In [50]:
data.head()

DeliveryTime  Cases  Distance
0         16.68      7       560
1         11.50      3       220
2         12.03      3       340
3         14.88      4        80
4         13.75      6       150

### Calculating beta values. 14-10-18

In [66]:
design = data.iloc[:,1:3]
design['1'] = 1

In [67]:
design = design[['1', 'Cases', 'Distance']]

In [68]:
design.head()

1  Cases  Distance
0  1      7       560
1  1      3       220
2  1      3       340
3  1      4        80
4  1      6       150

In [69]:
design = design.values

In [70]:
design

array([[   1,    7,  560],
       [   1,    3,  220],
       [   1,    3,  340],
       [   1,    4,   80],
       [   1,    6,  150],
       [   1,    7,  330],
       [   1,    2,  110],
       [   1,    7,  210],
       [   1,   30, 1460],
       [   1,    5,  605],
       [   1,   16,  688],
       [   1,   10,  215],
       [   1,    4,  255],
       [   1,    6,  462],
       [   1,    9,  448],
       [   1,   10,  776],
       [   1,    6,  200],
       [   1,    7,  132],
       [   1,    3,   36],
       [   1,   17,  770],
       [   1,   10,  140],
       [   1,   26,  810],
       [   1,    9,  450],
       [   1,    8,  635],
       [   1,    4,  150]])

In [71]:
delivery_time = np.array(data['DeliveryTime'])

In [72]:
delivery_time

array([ 16.68,  11.5 ,  12.03,  14.88,  13.75,  18.11,   8.  ,  17.83,
        79.24,  21.5 ,  40.33,  21.  ,  13.5 ,  19.75,  24.  ,  29.  ,
        15.35,  19.  ,   9.5 ,  35.1 ,  17.9 ,  52.32,  18.75,  19.83,
        10.75])

In [76]:
#Print Beta values
print(np.linalg.lstsq(design, delivery_time)[0])

[ 2.34123115  1.61590721  0.01438483]
